id: P82C8E26C
initial_creation_type: input
source_metadata:
  title: Chomden Rigpé Raldri
  language: fr
  description: 'Texts by and about Chomden Rigpé Raldri (bcom ldan rig pa''i ral gri,
    1227–1305), a celebrated scholar connected with Narthang Monastery:'
  volume:
    1fc561bd734f42b7b747aa1a42a871a8:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      parent: Abhidharma
created_at: '2022-02-28T22:48:44.149137'
last_modified_at: '2022-02-28T22:48:44.149139'
